# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'regTest' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for regTest

  target 'regTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'regTestTests' do
    inherit! :search_paths
    # Pods for testing
  end

end

target 'regTest-tvOS' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for regTest-tvOS

  target 'regTest-tvOSTests' do
    inherit! :search_paths
    # Pods for testing
  end

end
